# Generated by Django 4.1.2 on 2024-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
