# Generated by Django 4.1.2 on 2024-07-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_productos_delete_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
